; If you change any value below when game is running, you need to restart the game for the change to take effect.

[OGG-WinMM]
; Set to 1 to enable winmm.log with debug logging.
Debug = 0

; The folder name to read CDDA tracks (OGG files) from.
; NOTE: This must be a path relative to the DLL itself.
CDDAPath = Music

; Format for track names should have %d for track number.
; e.g. %02d means integer with up-to 2 leading zeroes.
; NOTE: default is Track%02d.ogg
CDDAFormat = Track_%02d.ogg

; Volume override for CDDA/MIDI/WAVE respectively. Range: Integer [0, 100]. 0: Mute; 100: Max.
; NOTE: All volumes are capped by Windows system master volume control.
CDDAVolume = 100
MIDIVolume = 100
WAVEVolume = 100
